### ISSUE TITLE
1.0.1 Stopped working on windows

### ISSUE THREAD

**Issue by dospolov** [vitejs/vite-plugin-basic-ssl#12]
1.0.1 Stopped working on windows

**Comment by dospolov** [comment]
![image](https://user-images.githubusercontent.com/670682/207681981-bd7b57cd-fcb3-4933-a5f7-3d3c43b22192.png)

**Comment by userquin** [comment]
@dospolov this plugin only generates the SSL/TLS certificate on `.npm_modules/.vite` folder, it doesn't install it on SO/browser.

If you want to install the certificate on the OS (to be used on chrome/edge/chromium/iexplorer):
- go to previous folder, open the file in text editor, copy to clipboard from `--- BEGIN CERTIFICATE ----` to `--- END CERTIFICATE ---` (including both lines) and paste in a new file called `localhost.cer` (you can also export certificate (public key) from browser options)
- double click on `localhost.cer` and click on Install button and follow instructions: Windows will ask you if you want to install the certificate as a new certificate authority, click YES and unsafe message will not be shown again.

**Comment by userquin** [comment]
@dospolov I'lll send a PR to include a small guide for Windows installation and Firefox (not using OS).

**Comment by hugoattal** [comment]
You should get this warning on Chrome, you can then click on "Show advanced", then "Continue toward 127.0.0.1".
![image](https://user-images.githubusercontent.com/4563971/207721365-804156b8-d093-4534-8e1e-705730d405ac.png)

Also, this plugin should only be used for local development. If you wish to expose a https version to the web, you should not use this plugin and instead use a proper web server (like NGINX) with a proper SSL certificate (for example, letsencrypt.org). But I imagine "local.simloud.be" actually redirect to localhost?

If you wish to install the certificate authority to your browser to hide this error, you can use this plugin instead: https://github.com/liuweiGL/vite-plugin-mkcert, BUT I advise against doing so.

- The error only shows once, then you just have to click on "continue" and the browser won't complain anymore
- The solution to copy/paste the certificate is not future-proof: if the node modules folder get deleted or if you have other project, you will have to do this multiple times because it will generate a new certificate each time
- The solution to copy/paste the certificate to manually install it to your browser is a real hassle and not the common usecase: I believe people using this plugin just want https to work quickly for testing purpose
- It's a bad practice to mess with certificate authorities

So I advise against giving those instructions in the readme.

**Comment by dospolov** [comment]
@hugoattal 
thanks for a detailed explanation

I mistakenly used `vite-plugin-basic-ssl` and `vite-plugin-mkcert` together. And updating `vite-plugin-basic-ssl` caused the original problem. Now I'm happy with `vite-plugin-mkcert` only
